# Generated by Django 4.1 on 2022-08-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
