# Generated by Django 4.1 on 2022-08-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0008_address_address_user_is_vendor_alter_user_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
