# Generated by Django 4.1 on 2022-08-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0009_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name_of_store',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
