# Generated by Django 4.1 on 2022-08-26 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0010_vendor_name_of_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='followers',
            field=models.ManyToManyField(related_name='vendor_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
