# Generated by Django 4.1 on 2022-08-31 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleus', '0013_inbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('discount', models.PositiveIntegerField(blank=True, default=0, help_text='Amount to be removed from ORIGINAL PRICE', null=True)),
                ('description', models.TextField(help_text='write the description in bullet points')),
                ('specifications', models.TextField(blank=True, help_text='write the specifications in bullet points', null=True)),
                ('key_features', models.TextField(blank=True, help_text='write the key-features, defining each key factorin bullet points', null=True)),
                ('picture_of_product_1', models.ImageField(upload_to='product_images')),
                ('picture_of_product_2', models.ImageField(blank=True, upload_to='product_images')),
                ('picture_of_product_3', models.ImageField(blank=True, upload_to='product_images')),
                ('picture_of_product_4', models.ImageField(blank=True, upload_to='product_images')),
                ('is_active', models.BooleanField(default=True)),
                ('labels', models.ManyToManyField(blank=True, to='main_store.labels')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_products', models.ManyToManyField(to='main_store.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_store.category')),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='input amount of days , you would like to run it for')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Kindly fill in your organization name, if youare making the report on behalf of your organization', max_length=20, null=True)),
                ('complainant_type', models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], max_length=20, null=True)),
                ('reason_for_report', models.CharField(choices=[('Product appears to be a replica', 'Product appears to be a replica'), ('Product Description Contains Inappropriate Information', 'Product Description Contains Inappropriate Information'), ('Profile description contains misleading information', 'Profile description contains misleading information'), ('Product is Illegal', 'Product is Illegal')], max_length=100, null=True)),
                ('additional_details', models.TextField(blank=True)),
                ('additional_file', models.FileField(blank=True, upload_to='complaint_files')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_store.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='Vilgax Store', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleus.vendor'),
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_moved', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('date_checked_out', models.DateField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_checked_out',),
                'unique_together': {('user', 'product', 'quantity', 'is_moved')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, null=True)),
                ('comments', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('date_commented', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='name of recipient', max_length=50)),
                ('address', models.CharField(max_length=5000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('delivery', models.CharField(choices=[('D', 'Door Delivery'), ('P', 'Pick Up Station')], max_length=1, null=True)),
                ('payment_method', models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('Pay With Card', 'Pay With Card'), ('Credit Card', 'Credit Card')], max_length=20, null=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_checked_out', models.DateTimeField(blank=True, null=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('ordered_products', models.ManyToManyField(blank=True, to='main_store.orderedproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'description', 'vendor')},
        ),
    ]
