# Generated by Django 4.1 on 2022-09-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedproduct',
            unique_together=set(),
        ),
    ]
